# Copy this file to secrets.toml and add your actual API key
# DO NOT commit secrets.toml to version control

#OPENROUTER_API_KEY = "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"
OPENROUTER_API_KEY="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"